name = "rna_at_most_two_short_helices_lean"
version = "1.0.0"
keywords = ["RNA", "formal verification", "Lean"]
defaultTargets = ["RNA"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3
linter.style.header = false # this standalone project does not use Mathlib's file-header policy

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.0-rc1"

[[lean_lib]]
name = "RNA"
